FROM --platform=$BUILDPLATFORM golang:1.26.3 AS build
ARG TARGETOS=linux TARGETARCH
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -o /lvmo-csi ./cmd/lvmo-csi
FROM ubuntu:24.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends lvm2 thin-provisioning-tools nfs-kernel-server targetcli-fb util-linux kmod e2fsprogs xfsprogs jq procps dbus && rm -rf /var/lib/apt/lists/*
COPY --from=build /lvmo-csi /usr/local/bin/lvmo-csi
COPY charts/lvmo-csi-storage-server/files/storage-server.sh /usr/local/bin/storage-server
COPY --chmod=755 charts/lvmo-csi-storage-server/files/exportfs /usr/local/sbin/exportfs
ENTRYPOINT ["bash", "/usr/local/bin/storage-server"]
