// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/v1/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{0}
}

type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_api_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateVolumeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bytes          int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Vg             string                 `protobuf:"bytes,3,opt,name=vg,proto3" json:"vg,omitempty"`
	Protocol       string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Filesystem     string                 `protobuf:"bytes,5,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	SourceSnapshot string                 `protobuf:"bytes,6,opt,name=source_snapshot,json=sourceSnapshot,proto3" json:"source_snapshot,omitempty"`
	SourceVolume   string                 `protobuf:"bytes,7,opt,name=source_volume,json=sourceVolume,proto3" json:"source_volume,omitempty"`
	Block          bool                   `protobuf:"varint,8,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_api_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeRequest) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *CreateVolumeRequest) GetVg() string {
	if x != nil {
		return x.Vg
	}
	return ""
}

func (x *CreateVolumeRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CreateVolumeRequest) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *CreateVolumeRequest) GetSourceSnapshot() string {
	if x != nil {
		return x.SourceSnapshot
	}
	return ""
}

func (x *CreateVolumeRequest) GetSourceVolume() string {
	if x != nil {
		return x.SourceVolume
	}
	return ""
}

func (x *CreateVolumeRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

type Volume struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bytes          int64                  `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Vg             string                 `protobuf:"bytes,4,opt,name=vg,proto3" json:"vg,omitempty"`
	Protocol       string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Filesystem     string                 `protobuf:"bytes,6,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Server         string                 `protobuf:"bytes,7,opt,name=server,proto3" json:"server,omitempty"`
	Path           string                 `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	Iqn            string                 `protobuf:"bytes,9,opt,name=iqn,proto3" json:"iqn,omitempty"`
	Lineage        string                 `protobuf:"bytes,10,opt,name=lineage,proto3" json:"lineage,omitempty"`
	Block          bool                   `protobuf:"varint,11,opt,name=block,proto3" json:"block,omitempty"`
	SourceSnapshot string                 `protobuf:"bytes,12,opt,name=source_snapshot,json=sourceSnapshot,proto3" json:"source_snapshot,omitempty"`
	SourceVolume   string                 `protobuf:"bytes,13,opt,name=source_volume,json=sourceVolume,proto3" json:"source_volume,omitempty"`
	Ready          bool                   `protobuf:"varint,14,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_api_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *Volume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Volume) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Volume) GetVg() string {
	if x != nil {
		return x.Vg
	}
	return ""
}

func (x *Volume) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Volume) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *Volume) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Volume) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Volume) GetIqn() string {
	if x != nil {
		return x.Iqn
	}
	return ""
}

func (x *Volume) GetLineage() string {
	if x != nil {
		return x.Lineage
	}
	return ""
}

func (x *Volume) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

func (x *Volume) GetSourceSnapshot() string {
	if x != nil {
		return x.SourceSnapshot
	}
	return ""
}

func (x *Volume) GetSourceVolume() string {
	if x != nil {
		return x.SourceVolume
	}
	return ""
}

func (x *Volume) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type Volumes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*Volume              `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volumes) Reset() {
	*x = Volumes{}
	mi := &file_api_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volumes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volumes) ProtoMessage() {}

func (x *Volumes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volumes.ProtoReflect.Descriptor instead.
func (*Volumes) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *Volumes) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type ExpandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bytes         int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	mi := &file_api_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ExpandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExpandRequest) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VolumeId      string                 `protobuf:"bytes,2,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_api_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VolumeId      string                 `protobuf:"bytes,3,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Vg            string                 `protobuf:"bytes,4,opt,name=vg,proto3" json:"vg,omitempty"`
	Bytes         int64                  `protobuf:"varint,5,opt,name=bytes,proto3" json:"bytes,omitempty"`
	CreatedUnix   int64                  `protobuf:"varint,6,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	Filesystem    string                 `protobuf:"bytes,7,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Lineage       string                 `protobuf:"bytes,8,opt,name=lineage,proto3" json:"lineage,omitempty"`
	Ready         bool                   `protobuf:"varint,9,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_api_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{7}
}

func (x *Snapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Snapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Snapshot) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *Snapshot) GetVg() string {
	if x != nil {
		return x.Vg
	}
	return ""
}

func (x *Snapshot) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Snapshot) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

func (x *Snapshot) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *Snapshot) GetLineage() string {
	if x != nil {
		return x.Lineage
	}
	return ""
}

func (x *Snapshot) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type Snapshots struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*Snapshot            `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshots) Reset() {
	*x = Snapshots{}
	mi := &file_api_v1_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshots) ProtoMessage() {}

func (x *Snapshots) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshots.ProtoReflect.Descriptor instead.
func (*Snapshots) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{8}
}

func (x *Snapshots) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type CapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vg            string                 `protobuf:"bytes,1,opt,name=vg,proto3" json:"vg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapacityRequest) Reset() {
	*x = CapacityRequest{}
	mi := &file_api_v1_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityRequest) ProtoMessage() {}

func (x *CapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityRequest.ProtoReflect.Descriptor instead.
func (*CapacityRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{9}
}

func (x *CapacityRequest) GetVg() string {
	if x != nil {
		return x.Vg
	}
	return ""
}

type Capacity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvailableBytes int64                  `protobuf:"varint,1,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_api_v1_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{10}
}

func (x *Capacity) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

type MetadataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Snapshot       string                 `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	BaseSnapshot   string                 `protobuf:"bytes,2,opt,name=base_snapshot,json=baseSnapshot,proto3" json:"base_snapshot,omitempty"`
	StartingOffset int64                  `protobuf:"varint,3,opt,name=starting_offset,json=startingOffset,proto3" json:"starting_offset,omitempty"`
	MaxResults     int32                  `protobuf:"varint,4,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_api_v1_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{11}
}

func (x *MetadataRequest) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *MetadataRequest) GetBaseSnapshot() string {
	if x != nil {
		return x.BaseSnapshot
	}
	return ""
}

func (x *MetadataRequest) GetStartingOffset() int64 {
	if x != nil {
		return x.StartingOffset
	}
	return 0
}

func (x *MetadataRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_api_v1_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{12}
}

func (x *Range) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Range) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type Ranges struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      int64                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Ranges        []*Range               `protobuf:"bytes,2,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ranges) Reset() {
	*x = Ranges{}
	mi := &file_api_v1_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ranges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ranges) ProtoMessage() {}

func (x *Ranges) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ranges.ProtoReflect.Descriptor instead.
func (*Ranges) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{13}
}

func (x *Ranges) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Ranges) GetRanges() []*Range {
	if x != nil {
		return x.Ranges
	}
	return nil
}

type VolumeLease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeLease) Reset() {
	*x = VolumeLease{}
	mi := &file_api_v1_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeLease) ProtoMessage() {}

func (x *VolumeLease) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeLease.ProtoReflect.Descriptor instead.
func (*VolumeLease) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{14}
}

func (x *VolumeLease) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *VolumeLease) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_api_v1_storage_proto protoreflect.FileDescriptor

const file_api_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/storage.proto\x12\alvmo.v1\"\a\n" +
	"\x05Empty\"\x14\n" +
	"\x02ID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xef\x01\n" +
	"\x13CreateVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\x12\x0e\n" +
	"\x02vg\x18\x03 \x01(\tR\x02vg\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x05 \x01(\tR\n" +
	"filesystem\x12'\n" +
	"\x0fsource_snapshot\x18\x06 \x01(\tR\x0esourceSnapshot\x12#\n" +
	"\rsource_volume\x18\a \x01(\tR\fsourceVolume\x12\x14\n" +
	"\x05block\x18\b \x01(\bR\x05block\"\xe0\x02\n" +
	"\x06Volume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x03R\x05bytes\x12\x0e\n" +
	"\x02vg\x18\x04 \x01(\tR\x02vg\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x06 \x01(\tR\n" +
	"filesystem\x12\x16\n" +
	"\x06server\x18\a \x01(\tR\x06server\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12\x10\n" +
	"\x03iqn\x18\t \x01(\tR\x03iqn\x12\x18\n" +
	"\alineage\x18\n" +
	" \x01(\tR\alineage\x12\x14\n" +
	"\x05block\x18\v \x01(\bR\x05block\x12'\n" +
	"\x0fsource_snapshot\x18\f \x01(\tR\x0esourceSnapshot\x12#\n" +
	"\rsource_volume\x18\r \x01(\tR\fsourceVolume\x12\x14\n" +
	"\x05ready\x18\x0e \x01(\bR\x05ready\"4\n" +
	"\aVolumes\x12)\n" +
	"\avolumes\x18\x01 \x03(\v2\x0f.lvmo.v1.VolumeR\avolumes\"5\n" +
	"\rExpandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\"B\n" +
	"\x0fSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tvolume_id\x18\x02 \x01(\tR\bvolumeId\"\xe4\x01\n" +
	"\bSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tvolume_id\x18\x03 \x01(\tR\bvolumeId\x12\x0e\n" +
	"\x02vg\x18\x04 \x01(\tR\x02vg\x12\x14\n" +
	"\x05bytes\x18\x05 \x01(\x03R\x05bytes\x12!\n" +
	"\fcreated_unix\x18\x06 \x01(\x03R\vcreatedUnix\x12\x1e\n" +
	"\n" +
	"filesystem\x18\a \x01(\tR\n" +
	"filesystem\x12\x18\n" +
	"\alineage\x18\b \x01(\tR\alineage\x12\x14\n" +
	"\x05ready\x18\t \x01(\bR\x05ready\"<\n" +
	"\tSnapshots\x12/\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x11.lvmo.v1.SnapshotR\tsnapshots\"!\n" +
	"\x0fCapacityRequest\x12\x0e\n" +
	"\x02vg\x18\x01 \x01(\tR\x02vg\"3\n" +
	"\bCapacity\x12'\n" +
	"\x0favailable_bytes\x18\x01 \x01(\x03R\x0eavailableBytes\"\x9c\x01\n" +
	"\x0fMetadataRequest\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\tR\bsnapshot\x12#\n" +
	"\rbase_snapshot\x18\x02 \x01(\tR\fbaseSnapshot\x12'\n" +
	"\x0fstarting_offset\x18\x03 \x01(\x03R\x0estartingOffset\x12\x1f\n" +
	"\vmax_results\x18\x04 \x01(\x05R\n" +
	"maxResults\"7\n" +
	"\x05Range\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\"L\n" +
	"\x06Ranges\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x03R\bcapacity\x12&\n" +
	"\x06ranges\x18\x02 \x03(\v2\x0e.lvmo.v1.RangeR\x06ranges\"C\n" +
	"\vVolumeLease\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId2\x90\x05\n" +
	"\aStorage\x125\n" +
	"\rAcquireVolume\x12\x14.lvmo.v1.VolumeLease\x1a\x0e.lvmo.v1.Empty\x125\n" +
	"\rReleaseVolume\x12\x14.lvmo.v1.VolumeLease\x1a\x0e.lvmo.v1.Empty\x12=\n" +
	"\fCreateVolume\x12\x1c.lvmo.v1.CreateVolumeRequest\x1a\x0f.lvmo.v1.Volume\x12)\n" +
	"\tGetVolume\x12\v.lvmo.v1.ID\x1a\x0f.lvmo.v1.Volume\x12+\n" +
	"\fDeleteVolume\x12\v.lvmo.v1.ID\x1a\x0e.lvmo.v1.Empty\x127\n" +
	"\fExpandVolume\x12\x16.lvmo.v1.ExpandRequest\x1a\x0f.lvmo.v1.Volume\x12/\n" +
	"\vListVolumes\x12\x0e.lvmo.v1.Empty\x1a\x10.lvmo.v1.Volumes\x12=\n" +
	"\x0eCreateSnapshot\x12\x18.lvmo.v1.SnapshotRequest\x1a\x11.lvmo.v1.Snapshot\x12-\n" +
	"\x0eDeleteSnapshot\x12\v.lvmo.v1.ID\x1a\x0e.lvmo.v1.Empty\x123\n" +
	"\rListSnapshots\x12\x0e.lvmo.v1.Empty\x1a\x12.lvmo.v1.Snapshots\x12:\n" +
	"\vGetCapacity\x12\x18.lvmo.v1.CapacityRequest\x1a\x11.lvmo.v1.Capacity\x127\n" +
	"\bMetadata\x12\x18.lvmo.v1.MetadataRequest\x1a\x0f.lvmo.v1.Ranges0\x01B2Z0github.com/michaelcourcy/lvmo-csi/api/v1;storageb\x06proto3"

var (
	file_api_v1_storage_proto_rawDescOnce sync.Once
	file_api_v1_storage_proto_rawDescData []byte
)

func file_api_v1_storage_proto_rawDescGZIP() []byte {
	file_api_v1_storage_proto_rawDescOnce.Do(func() {
		file_api_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_storage_proto_rawDesc), len(file_api_v1_storage_proto_rawDesc)))
	})
	return file_api_v1_storage_proto_rawDescData
}

var file_api_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_v1_storage_proto_goTypes = []any{
	(*Empty)(nil),               // 0: lvmo.v1.Empty
	(*ID)(nil),                  // 1: lvmo.v1.ID
	(*CreateVolumeRequest)(nil), // 2: lvmo.v1.CreateVolumeRequest
	(*Volume)(nil),              // 3: lvmo.v1.Volume
	(*Volumes)(nil),             // 4: lvmo.v1.Volumes
	(*ExpandRequest)(nil),       // 5: lvmo.v1.ExpandRequest
	(*SnapshotRequest)(nil),     // 6: lvmo.v1.SnapshotRequest
	(*Snapshot)(nil),            // 7: lvmo.v1.Snapshot
	(*Snapshots)(nil),           // 8: lvmo.v1.Snapshots
	(*CapacityRequest)(nil),     // 9: lvmo.v1.CapacityRequest
	(*Capacity)(nil),            // 10: lvmo.v1.Capacity
	(*MetadataRequest)(nil),     // 11: lvmo.v1.MetadataRequest
	(*Range)(nil),               // 12: lvmo.v1.Range
	(*Ranges)(nil),              // 13: lvmo.v1.Ranges
	(*VolumeLease)(nil),         // 14: lvmo.v1.VolumeLease
}
var file_api_v1_storage_proto_depIdxs = []int32{
	3,  // 0: lvmo.v1.Volumes.volumes:type_name -> lvmo.v1.Volume
	7,  // 1: lvmo.v1.Snapshots.snapshots:type_name -> lvmo.v1.Snapshot
	12, // 2: lvmo.v1.Ranges.ranges:type_name -> lvmo.v1.Range
	14, // 3: lvmo.v1.Storage.AcquireVolume:input_type -> lvmo.v1.VolumeLease
	14, // 4: lvmo.v1.Storage.ReleaseVolume:input_type -> lvmo.v1.VolumeLease
	2,  // 5: lvmo.v1.Storage.CreateVolume:input_type -> lvmo.v1.CreateVolumeRequest
	1,  // 6: lvmo.v1.Storage.GetVolume:input_type -> lvmo.v1.ID
	1,  // 7: lvmo.v1.Storage.DeleteVolume:input_type -> lvmo.v1.ID
	5,  // 8: lvmo.v1.Storage.ExpandVolume:input_type -> lvmo.v1.ExpandRequest
	0,  // 9: lvmo.v1.Storage.ListVolumes:input_type -> lvmo.v1.Empty
	6,  // 10: lvmo.v1.Storage.CreateSnapshot:input_type -> lvmo.v1.SnapshotRequest
	1,  // 11: lvmo.v1.Storage.DeleteSnapshot:input_type -> lvmo.v1.ID
	0,  // 12: lvmo.v1.Storage.ListSnapshots:input_type -> lvmo.v1.Empty
	9,  // 13: lvmo.v1.Storage.GetCapacity:input_type -> lvmo.v1.CapacityRequest
	11, // 14: lvmo.v1.Storage.Metadata:input_type -> lvmo.v1.MetadataRequest
	0,  // 15: lvmo.v1.Storage.AcquireVolume:output_type -> lvmo.v1.Empty
	0,  // 16: lvmo.v1.Storage.ReleaseVolume:output_type -> lvmo.v1.Empty
	3,  // 17: lvmo.v1.Storage.CreateVolume:output_type -> lvmo.v1.Volume
	3,  // 18: lvmo.v1.Storage.GetVolume:output_type -> lvmo.v1.Volume
	0,  // 19: lvmo.v1.Storage.DeleteVolume:output_type -> lvmo.v1.Empty
	3,  // 20: lvmo.v1.Storage.ExpandVolume:output_type -> lvmo.v1.Volume
	4,  // 21: lvmo.v1.Storage.ListVolumes:output_type -> lvmo.v1.Volumes
	7,  // 22: lvmo.v1.Storage.CreateSnapshot:output_type -> lvmo.v1.Snapshot
	0,  // 23: lvmo.v1.Storage.DeleteSnapshot:output_type -> lvmo.v1.Empty
	8,  // 24: lvmo.v1.Storage.ListSnapshots:output_type -> lvmo.v1.Snapshots
	10, // 25: lvmo.v1.Storage.GetCapacity:output_type -> lvmo.v1.Capacity
	13, // 26: lvmo.v1.Storage.Metadata:output_type -> lvmo.v1.Ranges
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_storage_proto_init() }
func file_api_v1_storage_proto_init() {
	if File_api_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_storage_proto_rawDesc), len(file_api_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_storage_proto_goTypes,
		DependencyIndexes: file_api_v1_storage_proto_depIdxs,
		MessageInfos:      file_api_v1_storage_proto_msgTypes,
	}.Build()
	File_api_v1_storage_proto = out.File
	file_api_v1_storage_proto_goTypes = nil
	file_api_v1_storage_proto_depIdxs = nil
}
