// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: api/v1/storage.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Storage_AcquireVolume_FullMethodName   = "/lvmo.v1.Storage/AcquireVolume"
	Storage_ReleaseVolume_FullMethodName   = "/lvmo.v1.Storage/ReleaseVolume"
	Storage_PublishVolume_FullMethodName   = "/lvmo.v1.Storage/PublishVolume"
	Storage_UnpublishVolume_FullMethodName = "/lvmo.v1.Storage/UnpublishVolume"
	Storage_Heartbeat_FullMethodName       = "/lvmo.v1.Storage/Heartbeat"
	Storage_FenceNode_FullMethodName       = "/lvmo.v1.Storage/FenceNode"
	Storage_CreateVolume_FullMethodName    = "/lvmo.v1.Storage/CreateVolume"
	Storage_GetVolume_FullMethodName       = "/lvmo.v1.Storage/GetVolume"
	Storage_DeleteVolume_FullMethodName    = "/lvmo.v1.Storage/DeleteVolume"
	Storage_ExpandVolume_FullMethodName    = "/lvmo.v1.Storage/ExpandVolume"
	Storage_ListVolumes_FullMethodName     = "/lvmo.v1.Storage/ListVolumes"
	Storage_CreateSnapshot_FullMethodName  = "/lvmo.v1.Storage/CreateSnapshot"
	Storage_DeleteSnapshot_FullMethodName  = "/lvmo.v1.Storage/DeleteSnapshot"
	Storage_ListSnapshots_FullMethodName   = "/lvmo.v1.Storage/ListSnapshots"
	Storage_GetCapacity_FullMethodName     = "/lvmo.v1.Storage/GetCapacity"
	Storage_Metadata_FullMethodName        = "/lvmo.v1.Storage/Metadata"
)

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	AcquireVolume(ctx context.Context, in *VolumeLease, opts ...grpc.CallOption) (*Empty, error)
	ReleaseVolume(ctx context.Context, in *VolumeLease, opts ...grpc.CallOption) (*Empty, error)
	// PublishVolume allows one node's iSCSI initiator to reach a volume's target;
	// UnpublishVolume revokes it and closes that initiator's sessions.
	PublishVolume(ctx context.Context, in *VolumePublish, opts ...grpc.CallOption) (*Empty, error)
	UnpublishVolume(ctx context.Context, in *VolumePublish, opts ...grpc.CallOption) (*Empty, error)
	// Heartbeat records that a node plugin can reach this server. FenceNode
	// revokes a node from every target, but only after it has been silent for
	// silence_seconds; it returns the volumes the node lost.
	Heartbeat(ctx context.Context, in *NodeHeartbeat, opts ...grpc.CallOption) (*Empty, error)
	FenceNode(ctx context.Context, in *NodeFence, opts ...grpc.CallOption) (*FencedVolumes, error)
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*Volume, error)
	GetVolume(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Volume, error)
	DeleteVolume(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error)
	ExpandVolume(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*Volume, error)
	ListVolumes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Volumes, error)
	CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error)
	DeleteSnapshot(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error)
	ListSnapshots(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Snapshots, error)
	GetCapacity(ctx context.Context, in *CapacityRequest, opts ...grpc.CallOption) (*Capacity, error)
	Metadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Ranges], error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) AcquireVolume(ctx context.Context, in *VolumeLease, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Storage_AcquireVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) ReleaseVolume(ctx context.Context, in *VolumeLease, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Storage_ReleaseVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) PublishVolume(ctx context.Context, in *VolumePublish, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Storage_PublishVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) UnpublishVolume(ctx context.Context, in *VolumePublish, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Storage_UnpublishVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Heartbeat(ctx context.Context, in *NodeHeartbeat, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Storage_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) FenceNode(ctx context.Context, in *NodeFence, opts ...grpc.CallOption) (*FencedVolumes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FencedVolumes)
	err := c.cc.Invoke(ctx, Storage_FenceNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*Volume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volume)
	err := c.cc.Invoke(ctx, Storage_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetVolume(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Volume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volume)
	err := c.cc.Invoke(ctx, Storage_GetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) DeleteVolume(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Storage_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) ExpandVolume(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*Volume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volume)
	err := c.cc.Invoke(ctx, Storage_ExpandVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) ListVolumes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Volumes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volumes)
	err := c.cc.Invoke(ctx, Storage_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, Storage_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) DeleteSnapshot(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Storage_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) ListSnapshots(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Snapshots, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshots)
	err := c.cc.Invoke(ctx, Storage_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetCapacity(ctx context.Context, in *CapacityRequest, opts ...grpc.CallOption) (*Capacity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capacity)
	err := c.cc.Invoke(ctx, Storage_GetCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Metadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Ranges], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Storage_ServiceDesc.Streams[0], Storage_Metadata_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetadataRequest, Ranges]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Storage_MetadataClient = grpc.ServerStreamingClient[Ranges]

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility.
type StorageServer interface {
	AcquireVolume(context.Context, *VolumeLease) (*Empty, error)
	ReleaseVolume(context.Context, *VolumeLease) (*Empty, error)
	// PublishVolume allows one node's iSCSI initiator to reach a volume's target;
	// UnpublishVolume revokes it and closes that initiator's sessions.
	PublishVolume(context.Context, *VolumePublish) (*Empty, error)
	UnpublishVolume(context.Context, *VolumePublish) (*Empty, error)
	// Heartbeat records that a node plugin can reach this server. FenceNode
	// revokes a node from every target, but only after it has been silent for
	// silence_seconds; it returns the volumes the node lost.
	Heartbeat(context.Context, *NodeHeartbeat) (*Empty, error)
	FenceNode(context.Context, *NodeFence) (*FencedVolumes, error)
	CreateVolume(context.Context, *CreateVolumeRequest) (*Volume, error)
	GetVolume(context.Context, *ID) (*Volume, error)
	DeleteVolume(context.Context, *ID) (*Empty, error)
	ExpandVolume(context.Context, *ExpandRequest) (*Volume, error)
	ListVolumes(context.Context, *Empty) (*Volumes, error)
	CreateSnapshot(context.Context, *SnapshotRequest) (*Snapshot, error)
	DeleteSnapshot(context.Context, *ID) (*Empty, error)
	ListSnapshots(context.Context, *Empty) (*Snapshots, error)
	GetCapacity(context.Context, *CapacityRequest) (*Capacity, error)
	Metadata(*MetadataRequest, grpc.ServerStreamingServer[Ranges]) error
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServer struct{}

func (UnimplementedStorageServer) AcquireVolume(context.Context, *VolumeLease) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireVolume not implemented")
}
func (UnimplementedStorageServer) ReleaseVolume(context.Context, *VolumeLease) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseVolume not implemented")
}
func (UnimplementedStorageServer) PublishVolume(context.Context, *VolumePublish) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishVolume not implemented")
}
func (UnimplementedStorageServer) UnpublishVolume(context.Context, *VolumePublish) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnpublishVolume not implemented")
}
func (UnimplementedStorageServer) Heartbeat(context.Context, *NodeHeartbeat) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedStorageServer) FenceNode(context.Context, *NodeFence) (*FencedVolumes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FenceNode not implemented")
}
func (UnimplementedStorageServer) CreateVolume(context.Context, *CreateVolumeRequest) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedStorageServer) GetVolume(context.Context, *ID) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolume not implemented")
}
func (UnimplementedStorageServer) DeleteVolume(context.Context, *ID) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedStorageServer) ExpandVolume(context.Context, *ExpandRequest) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpandVolume not implemented")
}
func (UnimplementedStorageServer) ListVolumes(context.Context, *Empty) (*Volumes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedStorageServer) CreateSnapshot(context.Context, *SnapshotRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedStorageServer) DeleteSnapshot(context.Context, *ID) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedStorageServer) ListSnapshots(context.Context, *Empty) (*Snapshots, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedStorageServer) GetCapacity(context.Context, *CapacityRequest) (*Capacity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapacity not implemented")
}
func (UnimplementedStorageServer) Metadata(*MetadataRequest, grpc.ServerStreamingServer[Ranges]) error {
	return status.Errorf(codes.Unimplemented, "method Metadata not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}
func (UnimplementedStorageServer) testEmbeddedByValue()                 {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s grpc.ServiceRegistrar, srv StorageServer) {
	// If the following call pancis, it indicates UnimplementedStorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Storage_ServiceDesc, srv)
}

func _Storage_AcquireVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeLease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).AcquireVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_AcquireVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).AcquireVolume(ctx, req.(*VolumeLease))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_ReleaseVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeLease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ReleaseVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_ReleaseVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ReleaseVolume(ctx, req.(*VolumeLease))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_PublishVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumePublish)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).PublishVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_PublishVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).PublishVolume(ctx, req.(*VolumePublish))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_UnpublishVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumePublish)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).UnpublishVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_UnpublishVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).UnpublishVolume(ctx, req.(*VolumePublish))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Heartbeat(ctx, req.(*NodeHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_FenceNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeFence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).FenceNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_FenceNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).FenceNode(ctx, req.(*NodeFence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_GetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetVolume(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).DeleteVolume(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_ExpandVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ExpandVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_ExpandVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ExpandVolume(ctx, req.(*ExpandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ListVolumes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CreateSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).DeleteSnapshot(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ListSnapshots(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_GetCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetCapacity(ctx, req.(*CapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Metadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MetadataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).Metadata(m, &grpc.GenericServerStream[MetadataRequest, Ranges]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Storage_MetadataServer = grpc.ServerStreamingServer[Ranges]

// Storage_ServiceDesc is the grpc.ServiceDesc for Storage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lvmo.v1.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireVolume",
			Handler:    _Storage_AcquireVolume_Handler,
		},
		{
			MethodName: "ReleaseVolume",
			Handler:    _Storage_ReleaseVolume_Handler,
		},
		{
			MethodName: "PublishVolume",
			Handler:    _Storage_PublishVolume_Handler,
		},
		{
			MethodName: "UnpublishVolume",
			Handler:    _Storage_UnpublishVolume_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Storage_Heartbeat_Handler,
		},
		{
			MethodName: "FenceNode",
			Handler:    _Storage_FenceNode_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _Storage_CreateVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _Storage_GetVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _Storage_DeleteVolume_Handler,
		},
		{
			MethodName: "ExpandVolume",
			Handler:    _Storage_ExpandVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _Storage_ListVolumes_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _Storage_CreateSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _Storage_DeleteSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _Storage_ListSnapshots_Handler,
		},
		{
			MethodName: "GetCapacity",
			Handler:    _Storage_GetCapacity_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Metadata",
			Handler:       _Storage_Metadata_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/storage.proto",
}
