name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with: {go-version-file: go.mod}
    - uses: azure/setup-helm@v4.3.0
      with: {version: v3.17.3}
    - run: make test lint release-binaries
    - uses: actions/upload-artifact@v4
      with: {name: linux-binaries, path: dist/}
